### ISSUE TITLE
Emoji rendering in Safari / Firefox on OSX

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/webassembly.sh#49]
<img width="311" alt="Screen Shot 2019-10-09 at 10 03 12" src="https://user-images.githubusercontent.com/5770194/66503422-12935300-ea7c-11e9-8298-937949c6de9e.png">

Both Safari and Firefox on OSX render half a heart!  This is in the `about` message.

This is a minor bug

edit: this happens on Firefox on Android too

**Comment by torch2424** [comment]
So this seems to work in [Hyper](https://hyper.is/):

<img width="550" alt="Screen Shot 2020-01-22 at 3 23 27 PM" src="https://user-images.githubusercontent.com/1448289/72943607-59efd780-3d2b-11ea-8d44-1d21e7ca9cd9.png">

And to my understanding, they use the [xterm-addon-ligatures](https://github.com/xtermjs/xterm-addon-ligatures#requirements), which fixes the way the fonts are rendered. However, I linked to the requirements, and this addon needs system access to use the native font renderer. So we are going to half to figure out how to implement this in the browser 🤔

**Comment by MarkMcCaskey** [comment]
It's rendering correctly in OSX Firefox now 🤷‍♂

**Comment by torch2424** [comment]
Oh nice, I guess it's fixed 😂 Nice, closing this 😄 👍
