### ISSUE TITLE
Support Asian Scripts

### ISSUE THREAD

**Issue by jayadevanraja** [wasmerio/webassembly.sh#62]
When I type
> echo Hello World

that is displayed perfectly. But Asian (Malayalam) text - which the browser supports - is not getting rendered properly.
> echo ജയദേവൻ
![echo-01](https://user-images.githubusercontent.com/7231689/69349748-504fe200-0c9e-11ea-85b8-a2062279b298.jpg)

This happens in both Firefox and Chrome.

**Comment by torch2424** [comment]
@Jayadevan-Vijayan 

Hello! Thank you for the issue! 😄 

I'll look into this, I think it may be involved with an issue with Xterm.js, so I'll do a quick investigation there.

Thanks again for finding this! 👍

**Comment by torch2424** [comment]
So please excuse my context on this.

So the characters should look something like: https://en.wikipedia.org/wiki/Malayalam .

But it appears they are being squished together correct? Like they don't have the right spacing?

I think this may be related to: https://github.com/xtermjs/xterm.js/issues/1709 if so.

Let me know if am I understanding this correctly @Jayadevan-Vijayan 😄 Thank you!

**Comment by Jayadevan-Vijayan** [comment]
Yes. That is true.

But some Asian scripts do render correctly. Also some European scripts may not be perfectly rendered. I feel that ẞß (in German) is not perfectly rendered, though quite readable.

![echo-02](https://user-images.githubusercontent.com/7231689/69461629-ff72e300-0d9c-11ea-8eb0-46062ad1db9e.jpg)

I tried entering this:
മലയാളം ಕನ್ನಡ বাংলা ଓଡ଼ିଆ తెలుగు தமிழ் සිංහල ÄäÖöÜüẞß

**Comment by torch2424** [comment]
@Jayadevan-Vijayan 

Thank you for clarifying! 😄 

Once I get the chance, I'll look into other issues mentioned on: https://github.com/xtermjs/xterm.js/issues/1709 And try to fix this downstream 👍

**Comment by torch2424** [comment]
So this seems to work in [Hyper](https://hyper.is/):

<img width="543" alt="Screen Shot 2020-01-22 at 3 28 46 PM" src="https://user-images.githubusercontent.com/1448289/72943827-e7cbc280-3d2b-11ea-865e-26db30d11854.png">

And to my understanding, they use the [xterm-addon-ligatures](https://github.com/xtermjs/xterm-addon-ligatures#requirements), which fixes the way the fonts are rendered. However, I linked to the requirements, and this addon needs system access to use the native font renderer. So we are going to half to figure out how to implement this in the browser 🤔

**Comment by torch2424** [comment]
In the meantime, going to close this issue, and move it into: https://github.com/wasmerio/wasmer-js/issues/185
