### ISSUE TITLE
"No such file or directory (os error 44)"

### ISSUE THREAD

**Issue by martin12333** [wasmerio/webassembly.sh#63]
**a test input**
(Thanks for the gif at https://github.com/wasmerio/webassembly.sh/pull/58 . )
I have tried with Chrome at https://webassembly.sh/ :
```
(drag and drop a file, e.g. icon_16.png)
ls /tmp
viu /tmp/icon_16.png
```

**and the result is**
```
$ 
File uploaded successfully to /tmp
→ /tmp/icon_16.png
$ ls /tmp
/tmp
$ viu /tmp/icon_16.png
No such file or directory (os error 44)
```

**Comment by torch2424** [comment]
@martin12333 Hello! Thank you for the issue! Sorry for the late reply, was the holidays in the US, and was out for that 😄 

So I went ahead and tried it out, and got in chrome:

<img width="906" alt="Screen Shot 2019-12-02 at 11 20 44 AM" src="https://user-images.githubusercontent.com/1448289/69988114-d3223980-14f5-11ea-931b-a0f694c6ef1c.png">

Could you share the file you are uploading? Perhaps it is an error in the image itself `viu` is having a hard time with? 🤔 

Thank you! 👍

**Comment by martin12333** [comment]
> Could you share the file you are uploading?
in my Chrome 78, it fails in the same way with any file e.g. https://user-images.githubusercontent.com/1448289/69988114-d3223980-14f5-11ea-931b-a0f694c6ef1c.png 
(renamed to 6.png)

**Comment by martin12333** [comment]
in my Chrome 78, there is a problem already after ls /tmp
![Screenshot from 2019-12-03 1412](https://user-images.githubusercontent.com/870886/70056958-a006a580-15dc-11ea-9510-a3f0d47cc4df.png)

**Comment by martin12333** [comment]
now it works in my Chrome in another profile
![icon_16](https://user-images.githubusercontent.com/870886/70067718-ff6db100-15ee-11ea-9a7d-0811d614c484.png)

![Screenshot from 2019-12-03 1725](https://user-images.githubusercontent.com/870886/70067592-c6cdd780-15ee-11ea-9c01-1e028a2bba74.png)

**Comment by torch2424** [comment]
@martin12333 

> EDIT: now it works in my Chrome in another profile

Ah perhaps it was a bad mismatch between chrome version? Or perhaps we had a bad service worker cache? 🤔 

> EDIT: there are still errors in the console, but maybe they are not so important.

Ah yeah, those are fine. The WASI Module sometimes will exit with an error, but give a success response, because it was ended early by the WASI program itself.

But, glad to hear things are working now! You mind if I close this issue? or is there another action item here? 😄 👍

**Comment by martin12333** [comment]
@torch2424 ... No, you can close this issue. Thank you.
