### ISSUE TITLE
"Error: undefined is not a function" when trying to run wasm binary

### ISSUE THREAD

**Issue by neelance** [wasmerio/webassembly.sh#73]
I tried running a wasm binary built with the Go compiler. I am able to run it locally with wasmer:
```
> wasmer run hello-go.wasm
Hello world!
```
However, I get an error when trying to run it with WebAssembly.sh:
```
$ hello-go
Error: undefined is not a function
```
Am I doing something wrong?

**Comment by syrusakbary** [comment]
It seems that should work.
Can you upload the wasm here so we can investigate? Thanks!

**Comment by syrusakbary** [comment]
I just tried the `hello-go` command in WebAssembly.sh and seems to be running fine:

```
$ wapm install neelance/hello-go@1.0.0
Package neelance/hello-go@1.0.0 installed successfully!
→ Installed commands: hello-go
$ hello-go
Hello world!
```

https://webassembly.sh/?run-command=wapm%20install%20neelance/hello-go@1.0.0

If that failed in your machine, can you try to do a hard-refresh on the website? (so cache is removed)

**Comment by neelance** [comment]
You are right, a hard-refresh solved it. Are there known caching issues?
